apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubex-deployment-probe
  namespace: kubex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubex-deployment-probe
  template:
    metadata:
      labels:
        app: kubex-deployment-probe
    spec:
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.9
